version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gunicorn:
    build:
      dockerfile: Dockerfile # Dockerfileのファイル名
    command: gunicorn besrun.wsgi:application --bind unix:/var/run/gunicorn/gunicorn.sock
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ./src:/src
      - gunicorn:/var/run/gunicorn
    container_name: gunicorn
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx
    depends_on:
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./src/static:/usr/share/nginx/html/static
      - gunicorn:/var/run/gunicorn
volumes:
  gunicorn:
    driver: local
  postgres_data: