version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gunicorn:
    build:
      context: ./docker # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile # Dockerfileのファイル名
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ${SRC_PATH}:/src
      - gunicorn:/var/run/gunicorn
    container_name: gunicorn
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    depends_on:
      - gunicorn
    ports:
      - "80:8000"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/usr/share/nginx/html/static
volumes:
  gunicorn:
    driver: local
  postgres_data: