version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn besrun.wsgi:application --bind unix:/var/run/gunicorn/gunicorn.sock
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - gunicorn:/var/run/gunicorn
      - ./src:/src
    container_name: gunicorn

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - gunicorn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/static:/usr/share/nginx/html/static
      - ${SSL_CRT_PATH}:/etc/nginx/certs/server.crt
      - ${SSL_KEY_PATH}:/etc/nginx/certs/server.key
      - ${SSL_PASS_PATH}:/etc/nginx/certs/server.password
      - gunicorn:/var/run/gunicorn
volumes:
  gunicorn:
    driver: local
  postgres_data: