# Generated by Django 5.0 on 2024-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestRun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestrun',
            name='video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
